# -*- coding: utf-8 -*-
"""Copy of data_preprocessing_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZrsZFpe3R04lk8gC-HYSmaiW4yyv082
"""


import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.metrics import pairwise_distances
from sklearn.utils import resample
from sklearn.metrics import adjusted_rand_score
import matplotlib.pyplot as plt

import pandas as pd
from pathlib import Path
#from google.colab import drive
import os
from pybaseball import playerid_reverse_lookup
import gc # 垃圾回收，手動釋放 RAM

# 掛載雲端硬碟

folder_path = 'data'

# 切換工作目錄到該資料夾
df = pd.read_csv('data/clustering_batting_stats_2018_2024.csv')
print(df.head())

"""分群

"""

print(df.head())
print(df.columns)

# =========================
# 2. 選擇 clustering 特徵
# =========================
# 建議用「比例型」或「打擊型態」特徵
# 不建議一開始放入 G、PA、AB，因為那比較像出賽機會，不一定是打擊類型

feature_cols = [
#"G", "PA", "AB", "H", "2B", "3B","HR", "BB", "K", "HBP", "SF"
"AVG", "OBP", "SLG", "ISO", "BB%", "K%", "wOBA","wRC+"
]

# 確認欄位存在
missing_cols = [col for col in feature_cols if col not in df.columns]
if missing_cols:
    raise ValueError(f"缺少欄位: {missing_cols}")

# 取出特徵資料
X = df[feature_cols].copy()

# 處理缺失值
X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(X.median())

# =========================
# 3. 標準化
# =========================

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# =========================
# 4. 用 Elbow Method 看適合的 cluster 數
# =========================

inertias = []
silhouette_scores = []
K_range = range(2, 11)
for k in K_range:
    kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=40,
    max_iter=100
)


    labels = kmeans.fit_predict(X_scaled)
    inertias.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(X_scaled, labels))

plt.figure(figsize=(8, 5))
plt.plot(K_range, inertias, marker="o")
plt.xlabel("Number of clusters")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(K_range, silhouette_scores, marker="o")
plt.xlabel("Number of clusters")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score by K")
plt.show()

# =========================
# 5. 正式做 KMeans clustering
# =========================

# 這裡先設定成 4 群，你可以依照 elbow / silhouette 結果調整
best_k = 4
kmeans = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=40,
    max_iter=100
)
df["cluster"] = kmeans.fit_predict(X_scaled)

# =========================
# 6. 查看每一群的特徵平均
# =========================
cluster_summary = df.groupby("cluster")[feature_cols].mean().round(3)
print("\nCluster Summary:")
print(cluster_summary)

# =========================
# 7. 幫 cluster 命名
# =========================

# 這裡可以先依照每群平均數人工命名
# 你可以看上面的 cluster_summary 後再調整名稱

cluster_type_map = {
    0: "低效能打者",
    1: "全能強棒型",
    2: "高三振長打盲砲型",
    3: "高接觸槍兵型",
}

df["type"] = df["cluster"].map(cluster_type_map)

# =========================
# 8. 用 PCA 畫出 cluster 視覺化
# =========================

# PC1 軸（橫軸）由左到右代表了「綜合進攻破壞力（wRC+）」的全面升級
# PC2 軸（縱軸）由下到上則區分了「擊球策略與型態（槍兵 vs. 盲砲）」

pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)
df["PC1"] = X_pca[:, 0]
df["PC2"] = X_pca[:, 1]
plt.figure(figsize=(9, 6))

for cluster_id in sorted(df["cluster"].unique()):
    temp = df[df["cluster"] == cluster_id]
    plt.scatter(
        temp["PC1"],
        temp["PC2"],
        label=f"Cluster {cluster_id}",
        alpha=0.7
    )

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("Batter Clustering PCA Plot")
plt.legend()
plt.show()

# =========================
# 9. 輸出結果
# =========================

output_path = "data/batting_stats_2018_2024_with_clusters.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")
print(f"\n已輸出檔案: {output_path}")

# ==============================================================================
# 10. 模型分類能力驗證：聚類穩定性評估 (Cluster Stability via Bootstrap)
# ==============================================================================
# 邏輯參考 R 語言的 clusterboot (fpc package)
# 透過重複抽樣驗證：原本被分在同一個特型（槍兵/盲砲/強棒）的打者，在新的抽樣中是否依然穩定綁在一起。
print("\n--- 開始進行分群穩定度驗證 (Bootstrap Stability Analysis) ---")

n_iterations = 100  # 拔靴法重複抽樣次數
stability_scores = []

# 拿你在步驟 5 已經訓練好的 KMeans 模型標籤作為基準 (Base Labels)
base_labels = df["cluster"].values

for i in range(1, n_iterations + 1):
    # 1. 有放回的隨機重抽樣 (Bootstrap)
    X_resampled, resampled_indices = resample(
        X_scaled,
        np.arange(len(X_scaled)),
        random_state=i + 42  # 確保每次隨機不重複且可復現
    )

    # 2. 用一模一樣的模型參數去訓練抽樣後的資料
    kmeans_boot = KMeans(
        n_clusters=best_k,
        random_state=i + 42,
        n_init=40,
        max_iter=100
    )
    kmeans_boot.fit(X_resampled)

    # 3. 讓新模型回頭預測「原始完整資料」的標籤
    pred_labels_on_base = kmeans_boot.predict(X_scaled)

    # 4. 計算原始分群與新分群之間的相似度 (ARI 分數)
    # ARI 分數範圍為 -1 到 1。越接近 1 代表重抽樣後分群結構越穩定、越不容易被打亂。
    score = adjusted_rand_score(base_labels, pred_labels_on_base)
    stability_scores.append(score)

    if i % 20 == 0:
        print(f"已完成 {i}/{n_iterations} 次模擬抽樣...")

# ==============================================================================
# 11. 輸出驗證結果與繪圖
# ==============================================================================
mean_stability = np.mean(stability_scores)
print(f"\n【驗證結論】")
print(f"經過 {n_iterations} 次 Bootstrap 模擬，平均分群穩定度 (ARI): {mean_stability:.3f}")

# 解讀指南
if mean_stability >= 0.75:
    print("👉 結論：分群結構【極度穩定】！這四種打者型態（工兵、槍兵、盲砲、強棒）是資料中非常扎實的特徵結構。")
elif mean_stability >= 0.55:
    print("👉 結論：分群結構【具備良好穩定性】。雖然打者數據連續且邊界重疊，但這四個分類具有明顯且有意義的特質趨勢。")
else:
    print("👉 結論：分群結構【較不穩定】。結果容易受到樣本變動影響，建議重新篩選特徵或調整 K 值。")

# 繪製穩定度分佈圖
plt.figure(figsize=(8, 4))
plt.plot(range(1, n_iterations + 1), stability_scores, color="darkcyan", alpha=0.6, label="ARI per iteration")
plt.axhline(y=mean_stability, color="red", linestyle="--", linewidth=1.5, label=f"Mean ARI ({mean_stability:.3f})")
plt.xlabel("Bootstrap Iteration")
plt.ylabel("Stability Score (ARI)")
plt.title("Cluster Stability Analysis (Bootstrap)")
plt.ylim(0, 1.05)
plt.legend()
plt.grid(True, linestyle=":", alpha=0.6)
plt.show()

player_name = "Shohei Ohtani"

one_player_history = df[
    df["Name"].str.contains(player_name, case=False, na=False)
][["Name", "Year", "cluster", "type"]].sort_values("Year")

print(one_player_history)

"""找打者的function

"""

def find_replacement_batters(
    df,
    target_name,
    target_year,
    top_n=10,
    same_cluster=True
):
    similarity_features = [
        "AVG", "OBP", "SLG", "OPS",
        "ISO", "BB%", "K%",
        "wOBA", "wRC+"
    ]

    missing_cols = [col for col in similarity_features if col not in df.columns]
    if missing_cols:
        raise ValueError(f"缺少欄位: {missing_cols}")

    if "cluster" not in df.columns:
        raise ValueError("資料中沒有 cluster 欄位，請先完成 KMeans clustering。")

    work_df = df.copy()

    X = work_df[similarity_features].copy()
    X = X.replace([np.inf, -np.inf], np.nan)
    X = X.fillna(X.median())

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    scaled_cols = [col + "_scaled" for col in similarity_features]

    for i, col in enumerate(scaled_cols):
        work_df[col] = X_scaled[:, i]

    target_rows = work_df[
        (work_df["Name"].str.contains(target_name, case=False, na=False)) &
        (work_df["Year"] == target_year)
    ]

    if len(target_rows) == 0:
        raise ValueError("找不到這位打者在該年份的資料，請確認姓名或年份。")

    target = target_rows.iloc[0]
    target_cluster = target["cluster"]

    if same_cluster:
        candidate_pool = work_df[
            (work_df["Year"] == target_year) &
            (work_df["cluster"] == target_cluster) &
            (work_df["Name"] != target["Name"])
        ].copy()
    else:
        candidate_pool = work_df[
            (work_df["Year"] == target_year) &
            (work_df["Name"] != target["Name"])
        ].copy()

    if len(candidate_pool) == 0:
        raise ValueError("沒有找到可比較的候選打者。")

    target_vector = target[scaled_cols].values.reshape(1, -1)
    candidate_vectors = candidate_pool[scaled_cols].values

    candidate_pool["distance"] = pairwise_distances(
        candidate_vectors,
        target_vector,
        metric="euclidean"
    ).flatten()

    result_cols = [
        "Name", "Year", "cluster", "type", "distance",
        "AVG", "OBP", "SLG", "OPS", "ISO",
        "BB%", "K%", "wOBA", "wRC+",
        "HR", "WAR"
    ]

    available_cols = [col for col in result_cols if col in candidate_pool.columns]

    return candidate_pool.sort_values("distance")[available_cols].head(top_n)

"""**找出前十位相近打者**"""

find_replacement_batters(
    df=df,
    target_name="Shohei Ohtani",
    target_year=2019,
    top_n=10,
    same_cluster=True
)
